### ISSUE TITLE
Build Failure on branches main, 0.24.0, and 0.23.0

### ISSUE THREAD

**Issue by mackoj** [giginet/Scipio#155]
Hello 👋,

I’m encountering build issues when trying to compile the project on the main, 0.24, and 0.23 branches.

It would be helpful to have a streamlined way to build the project, such as using `mint run giginet/Scipio@0.24.0` or similar.

### Branch-specific Issues

Main Branch:
```
[Basics#51] no such module 'SPMSQLite3'
[Basics#51] /Users/blablabla/Developer/Scipio/.build/checkouts/swift-package-manager/Sources/Basics/SQLite.swift:18:8: error: no such module 'SPMSQLite3'
import SPMSQLite3
```

0.24 Branch:
Compilation stops due to a linker error with Yams, specifically related to missing symbols for YAML functions.
```
[Yams#58] Link Yams (arm64)
    cd /Users/blablabla/Developer/Scipio/.build/checkouts/Yams
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -Xlinker -reproducible -target arm64-apple-macos10.13 -dynamiclib -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.1.sdk -Os -L/Users/blablabla/Developer/Scipio/.build/scipio/DerivedData/Intermediates.noindex/EagerLinkingTBDs/Release -L/Users/blablabla/Developer/Scipio/.build/scipio/DerivedData/Products/Release -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib -L/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib -F/Users/blablabla/Developer/Scipio/.build/scipio/DerivedData/Intermediates.noindex/EagerLinkingTBDs/Release -F/Users/blablabla/Developer/Scipio/.build/scipio/DerivedData/Products/Release -F/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks -iframework /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks -filelist /Users/blablabla/Developer/Scipio/.build/scipio/DerivedData/Intermediates.noindex/Yams.build/Release/Yams.build/Objects-normal/arm64/Yams.LinkFileList -install_name @rpath/Yams.framework/Versions/A/Yams -Xlinker -rpath -Xlinker /usr/lib/swift -Xlinker -object_path_lto -Xlinker /Users/blablabla/Developer/Scipio/.build/scipio/DerivedData/Intermediates.noindex/Yams.build/Release/Yams.build/Objects-normal/arm64/Yams_lto.o -fobjc-link-runtime -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx -L/usr/lib/swift -Xlinker -add_ast_path -Xlinker /Users/blablabla/Developer/Scipio/.build/scipio/DerivedData/Intermediates.noindex/Yams.build/Release/Yams.build/Objects-normal/arm64/Yams.swiftmodule -Wl,-no_warn_duplicate_libraries -Xlinker -dependency_info -Xlinker /Users/blablabla/Developer/Scipio/.build/scipio/DerivedData/Intermediates.noindex/Yams.build/Release/Yams.build/Objects-normal/arm64/Yams_dependency_info.dat -o /Users/blablabla/Developer/Scipio/.build/scipio/DerivedData/Intermediates.noindex/Yams.build/Release/Yams.build/Objects-normal/arm64/Binary/Yams

[Yams#58] Undefined symbol: _yaml_document_end_event_initialize
[Yams#58] Undefined symbol: _yaml_document_start_event_initialize
[Yams#58] Undefined symbol: _yaml_emitter_delete
[Yams#58] Undefined symbol: _yaml_emitter_emit
[Yams#58] Undefined symbol: _yaml_emitter_initialize
[Yams#58] Undefined symbol: _yaml_emitter_set_break
[Yams#58] Undefined symbol: _yaml_emitter_set_canonical
[Yams#58] Undefined symbol: _yaml_emitter_set_encoding
[Yams#58] Undefined symbol: _yaml_emitter_set_indent
[Yams#58] Undefined symbol: _yaml_emitter_set_output
[Yams#58] Undefined symbol: _yaml_emitter_set_unicode
[Yams#58] Undefined symbol: _yaml_emitter_set_width
[Yams#58] Undefined symbol: _yaml_event_delete
[Yams#58] Undefined symbol: _yaml_mapping_end_event_initialize
[Yams#58] Undefined symbol: _yaml_mapping_start_event_initialize
[Yams#58] Undefined symbol: _yaml_parser_delete
[Yams#58] Undefined symbol: _yaml_parser_initialize
[Yams#58] Undefined symbol: _yaml_parser_parse
[Yams#58] Undefined symbol: _yaml_parser_set_encoding
[Yams#58] Undefined symbol: _yaml_parser_set_input_string
[Yams#58] Undefined symbol: _yaml_scalar_event_initialize
[Yams#58] Undefined symbol: _yaml_sequence_end_event_initialize
[Yams#58] Undefined symbol: _yaml_sequence_start_event_initialize
[Yams#58] Undefined symbol: _yaml_stream_end_event_initialize
[Yams#58] Undefined symbol: _yaml_stream_start_event_initialize
[Yams#57] Undefined symbol: _yaml_document_end_event_initialize
[Yams#57] Undefined symbol: _yaml_document_start_event_initialize
[Yams#57] Undefined symbol: _yaml_emitter_delete
[Yams#57] Undefined symbol: _yaml_emitter_emit
[Yams#57] Undefined symbol: _yaml_emitter_initialize
[Yams#57] Undefined symbol: _yaml_emitter_set_break
[Yams#57] Undefined symbol: _yaml_emitter_set_canonical
[Yams#57] Undefined symbol: _yaml_emitter_set_encoding
[Yams#57] Undefined symbol: _yaml_emitter_set_indent
[Yams#57] Undefined symbol: _yaml_emitter_set_output
[Yams#57] Undefined symbol: _yaml_emitter_set_unicode
[Yams#57] Undefined symbol: _yaml_emitter_set_width
[Yams#57] Undefined symbol: _yaml_event_delete
[Yams#57] Undefined symbol: _yaml_mapping_end_event_initialize
[Yams#57] Undefined symbol: _yaml_mapping_start_event_initialize
[Yams#57] Undefined symbol: _yaml_parser_delete
[Yams#57] Undefined symbol: _yaml_parser_initialize
[Yams#57] Undefined symbol: _yaml_parser_parse
[Yams#57] Undefined symbol: _yaml_parser_set_encoding
[Yams#57] Undefined symbol: _yaml_parser_set_input_string
[Yams#57] Undefined symbol: _yaml_scalar_event_initialize
[Yams#57] Undefined symbol: _yaml_sequence_end_event_initialize
[Yams#57] Undefined symbol: _yaml_sequence_start_event_initialize
[Yams#57] Undefined symbol: _yaml_stream_end_event_initialize
[Yams#57] Undefined symbol: _yaml_stream_start_event_initialize
[Yams#58] Linker command failed with exit code 1 (use -v to see invocation)
[Yams#58] Undefined symbols for architecture arm64:
  "_yaml_document_end_event_initialize", referenced from:
      Yams.Emitter.serialize(node: Yams.Node) throws -> () in Emitter.o
  "_yaml_document_start_event_initialize", referenced from:
      Yams.Emitter.serialize(node: Yams.Node) throws -> () in Emitter.o
  "_yaml_emitter_delete", referenced from:
      Yams.Emitter.deinit in Emitter.o
      Yams.Emitter.__deallocating_deinit in Emitter.o
  "_yaml_emitter_emit", referenced from:
      Yams.Emitter.open() throws -> () in Emitter.o
      Yams.Emitter.serialize(node: Yams.Node) throws -> () in Emitter.o
      Yams.Emitter.serialize(node: Yams.Node) throws -> () in Emitter.o
      Yams.Emitter.close() throws -> () in Emitter.o
      Yams.Emitter.(serializeScalar in _ED6AA6759560A6062E809BF7E6589292)(Yams.Node.Scalar) throws -> () in Emitter.o
      Yams.Emitter.(serializeSequence in _ED6AA6759560A6062E809BF7E6589292)(Yams.Node.Sequence) throws -> () in Emitter.o
      Yams.Emitter.(serializeSequence in _ED6AA6759560A6062E809BF7E6589292)(Yams.Node.Sequence) throws -> () in Emitter.o
      ...
  "_yaml_emitter_initialize", referenced from:
      Yams.Emitter.init(canonical: Swift.Bool, indent: Swift.Int, width: Swift.Int, allowUnicode: Swift.Bool, lineBreak: Yams.Emitter.LineBreak, explicitStart: Swift.Bool, explicitEnd: Swift.Bool, version: (major: Swift.Int, minor: Swift.Int)?, sortKeys: Swift.Bool, sequenceStyle: Yams.Node.Sequence.Style, mappingStyle: Yams.Node.Mapping.Style) -> Yams.Emitter in Emitter.o
  "_yaml_emitter_set_break", referenced from:
      Yams.Emitter.(applyOptionsToEmitter in _ED6AA6759560A6062E809BF7E6589292)() -> () in Emitter.o
  "_yaml_emitter_set_canonical", referenced from:
      Yams.Emitter.(applyOptionsToEmitter in _ED6AA6759560A6062E809BF7E6589292)() -> () in Emitter.o
  "_yaml_emitter_set_encoding", referenced from:
      Yams.Emitter.init(canonical: Swift.Bool, indent: Swift.Int, width: Swift.Int, allowUnicode: Swift.Bool, lineBreak: Yams.Emitter.LineBreak, explicitStart: Swift.Bool, explicitEnd: Swift.Bool, version: (major: Swift.Int, minor: Swift.Int)?, sortKeys: Swift.Bool, sequenceStyle: Yams.Node.Sequence.Style, mappingStyle: Yams.Node.Mapping.Style) -> Yams.Emitter in Emitter.o
  "_yaml_emitter_set_indent", referenced from:
      Yams.Emitter.(applyOptionsToEmitter in _ED6AA6759560A6062E809BF7E6589292)() -> () in Emitter.o
  "_yaml_emitter_set_output", referenced from:
      Yams.Emitter.init(canonical: Swift.Bool, indent: Swift.Int, width: Swift.Int, allowUnicode: Swift.Bool, lineBreak: Yams.Emitter.LineBreak, explicitStart: Swift.Bool, explicitEnd: Swift.Bool, version: (major: Swift.Int, minor: Swift.Int)?, sortKeys: Swift.Bool, sequenceStyle: Yams.Node.Sequence.Style, mappingStyle: Yams.Node.Mapping.Style) -> Yams.Emitter in Emitter.o
  "_yaml_emitter_set_unicode", referenced from:
      Yams.Emitter.(applyOptionsToEmitter in _ED6AA6759560A6062E809BF7E6589292)() -> () in Emitter.o
  "_yaml_emitter_set_width", referenced from:
      Yams.Emitter.(applyOptionsToEmitter in _ED6AA6759560A6062E809BF7E6589292)() -> () in Emitter.o
  "_yaml_event_delete", referenced from:
      Yams.Parser.singleRoot() throws -> Yams.Node? in Parser.o
      Yams.Parser.singleRoot() throws -> Yams.Node? in Parser.o
      Yams.Parser.singleRoot() throws -> Yams.Node? in Parser.o
      Yams.Parser.singleRoot() throws -> Yams.Node? in Parser.o
      Yams.Parser.singleRoot() throws -> Yams.Node? in Parser.o
      Yams.Parser.nextRoot() throws -> Yams.Node? in Parser.o
      Yams.Parser.nextRoot() throws -> Yams.Node? in Parser.o
      ...
  "_yaml_mapping_end_event_initialize", referenced from:
      Yams.Emitter.(serializeMapping in _ED6AA6759560A6062E809BF7E6589292)(Yams.Node.Mapping) throws -> () in Emitter.o
  "_yaml_mapping_start_event_initialize", referenced from:
      Yams.Emitter.(serializeMapping in _ED6AA6759560A6062E809BF7E6589292)(Yams.Node.Mapping) throws -> () in Emitter.o
  "_yaml_parser_delete", referenced from:
      Yams.Parser.deinit in Parser.o
      Yams.Parser.__deallocating_deinit in Parser.o
  "_yaml_parser_initialize", referenced from:
      Yams.Parser.init(yaml: Swift.String, resolver: Yams.Resolver, constructor: Yams.Constructor, encoding: Yams.Parser.Encoding) throws -> Yams.Parser in Parser.o
  "_yaml_parser_parse", referenced from:
      Yams.Parser.singleRoot() throws -> Yams.Node? in Parser.o
      Yams.Parser.singleRoot() throws -> Yams.Node? in Parser.o
      Yams.Parser.nextRoot() throws -> Yams.Node? in Parser.o
      Yams.Parser.init(yaml: Swift.String, resolver: Yams.Resolver, constructor: Yams.Constructor, encoding: Yams.Parser.Encoding) throws -> Yams.Parser in Parser.o
      Yams.Parser.(startParse in _61DADACE4404A34EA4A7CBD5917BB545)(with: Swift.UnsafeBufferPointer<Swift.UInt8>) throws -> () in Parser.o
      Yams.Parser.(startParse in _61DADACE4404A34EA4A7CBD5917BB545)(with: Swift.UnsafeRawBufferPointer) throws -> () in Parser.o
      Yams.Parser.(loadDocument in _61DADACE4404A34EA4A7CBD5917BB545)() throws -> Yams.Node in Parser.o
      Yams.Parser.(loadDocument in _61DADACE4404A34EA4A7CBD5917BB545)() throws -> Yams.Node in Parser.o
      ...
  "_yaml_parser_set_encoding", referenced from:
      Yams.Parser.init(yaml: Swift.String, resolver: Yams.Resolver, constructor: Yams.Constructor, encoding: Yams.Parser.Encoding) throws -> Yams.Parser in Parser.o
      Yams.Parser.init(yaml: Swift.String, resolver: Yams.Resolver, constructor: Yams.Constructor, encoding: Yams.Parser.Encoding) throws -> Yams.Parser in Parser.o
  "_yaml_parser_set_input_string", referenced from:
      Yams.Parser.init(yaml: Swift.String, resolver: Yams.Resolver, constructor: Yams.Constructor, encoding: Yams.Parser.Encoding) throws -> Yams.Parser in Parser.o
      Yams.Parser.(startParse in _61DADACE4404A34EA4A7CBD5917BB545)(with: Swift.UnsafeBufferPointer<Swift.UInt8>) throws -> () in Parser.o
      Yams.Parser.(startParse in _61DADACE4404A34EA4A7CBD5917BB545)(with: Swift.UnsafeRawBufferPointer) throws -> () in Parser.o
  "_yaml_scalar_event_initialize", referenced from:
      Yams.Emitter.(serializeScalar in _ED6AA6759560A6062E809BF7E6589292)(Yams.Node.Scalar) throws -> () in Emitter.o
  "_yaml_sequence_end_event_initialize", referenced from:
      Yams.Emitter.(serializeSequence in _ED6AA6759560A6062E809BF7E6589292)(Yams.Node.Sequence) throws -> () in Emitter.o
  "_yaml_sequence_start_event_initialize", referenced from:
      Yams.Emitter.(serializeSequence in _ED6AA6759560A6062E809BF7E6589292)(Yams.Node.Sequence) throws -> () in Emitter.o
  "_yaml_stream_end_event_initialize", referenced from:
      Yams.Emitter.close() throws -> () in Emitter.o
  "_yaml_stream_start_event_initialize", referenced from:
      Yams.Emitter.open() throws -> () in Emitter.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

[Yams#58] failed
[Yams#57] Linker command failed with exit code 1 (use -v to see invocation)
[Yams#57] Undefined symbols for architecture x86_64:
  "_yaml_document_end_event_initialize", referenced from:
      Yams.Emitter.serialize(node: Yams.Node) throws -> () in Emitter.o
  "_yaml_document_start_event_initialize", referenced from:
      Yams.Emitter.serialize(node: Yams.Node) throws -> () in Emitter.o
  "_yaml_emitter_delete", referenced from:
      Yams.Emitter.deinit in Emitter.o
      Yams.Emitter.__deallocating_deinit in Emitter.o
  "_yaml_emitter_emit", referenced from:
      Yams.Emitter.open() throws -> () in Emitter.o
      Yams.Emitter.serialize(node: Yams.Node) throws -> () in Emitter.o
      Yams.Emitter.serialize(node: Yams.Node) throws -> () in Emitter.o
      Yams.Emitter.close() throws -> () in Emitter.o
      Yams.Emitter.(serializeScalar in _ED6AA6759560A6062E809BF7E6589292)(Yams.Node.Scalar) throws -> () in Emitter.o
      Yams.Emitter.(serializeSequence in _ED6AA6759560A6062E809BF7E6589292)(Yams.Node.Sequence) throws -> () in Emitter.o
      Yams.Emitter.(serializeSequence in _ED6AA6759560A6062E809BF7E6589292)(Yams.Node.Sequence) throws -> () in Emitter.o
      ...
  "_yaml_emitter_initialize", referenced from:
      Yams.Emitter.init(canonical: Swift.Bool, indent: Swift.Int, width: Swift.Int, allowUnicode: Swift.Bool, lineBreak: Yams.Emitter.LineBreak, explicitStart: Swift.Bool, explicitEnd: Swift.Bool, version: (major: Swift.Int, minor: Swift.Int)?, sortKeys: Swift.Bool, sequenceStyle: Yams.Node.Sequence.Style, mappingStyle: Yams.Node.Mapping.Style) -> Yams.Emitter in Emitter.o
  "_yaml_emitter_set_break", referenced from:
      Yams.Emitter.(applyOptionsToEmitter in _ED6AA6759560A6062E809BF7E6589292)() -> () in Emitter.o
  "_yaml_emitter_set_canonical", referenced from:
      Yams.Emitter.(applyOptionsToEmitter in _ED6AA6759560A6062E809BF7E6589292)() -> () in Emitter.o
  "_yaml_emitter_set_encoding", referenced from:
      Yams.Emitter.init(canonical: Swift.Bool, indent: Swift.Int, width: Swift.Int, allowUnicode: Swift.Bool, lineBreak: Yams.Emitter.LineBreak, explicitStart: Swift.Bool, explicitEnd: Swift.Bool, version: (major: Swift.Int, minor: Swift.Int)?, sortKeys: Swift.Bool, sequenceStyle: Yams.Node.Sequence.Style, mappingStyle: Yams.Node.Mapping.Style) -> Yams.Emitter in Emitter.o
  "_yaml_emitter_set_indent", referenced from:
      Yams.Emitter.(applyOptionsToEmitter in _ED6AA6759560A6062E809BF7E6589292)() -> () in Emitter.o
  "_yaml_emitter_set_output", referenced from:
      Yams.Emitter.init(canonical: Swift.Bool, indent: Swift.Int, width: Swift.Int, allowUnicode: Swift.Bool, lineBreak: Yams.Emitter.LineBreak, explicitStart: Swift.Bool, explicitEnd: Swift.Bool, version: (major: Swift.Int, minor: Swift.Int)?, sortKeys: Swift.Bool, sequenceStyle: Yams.Node.Sequence.Style, mappingStyle: Yams.Node.Mapping.Style) -> Yams.Emitter in Emitter.o
  "_yaml_emitter_set_unicode", referenced from:
      Yams.Emitter.(applyOptionsToEmitter in _ED6AA6759560A6062E809BF7E6589292)() -> () in Emitter.o
  "_yaml_emitter_set_width", referenced from:
      Yams.Emitter.(applyOptionsToEmitter in _ED6AA6759560A6062E809BF7E6589292)() -> () in Emitter.o
  "_yaml_event_delete", referenced from:
      Yams.Parser.singleRoot() throws -> Yams.Node? in Parser.o
      Yams.Parser.singleRoot() throws -> Yams.Node? in Parser.o
      Yams.Parser.singleRoot() throws -> Yams.Node? in Parser.o
      Yams.Parser.singleRoot() throws -> Yams.Node? in Parser.o
      Yams.Parser.singleRoot() throws -> Yams.Node? in Parser.o
      Yams.Parser.nextRoot() throws -> Yams.Node? in Parser.o
      Yams.Parser.nextRoot() throws -> Yams.Node? in Parser.o
      ...
  "_yaml_mapping_end_event_initialize", referenced from:
      Yams.Emitter.(serializeMapping in _ED6AA6759560A6062E809BF7E6589292)(Yams.Node.Mapping) throws -> () in Emitter.o
  "_yaml_mapping_start_event_initialize", referenced from:
      Yams.Emitter.(serializeMapping in _ED6AA6759560A6062E809BF7E6589292)(Yams.Node.Mapping) throws -> () in Emitter.o
  "_yaml_parser_delete", referenced from:
      Yams.Parser.deinit in Parser.o
      Yams.Parser.__deallocating_deinit in Parser.o
  "_yaml_parser_initialize", referenced from:
      Yams.Parser.init(yaml: Swift.String, resolver: Yams.Resolver, constructor: Yams.Constructor, encoding: Yams.Parser.Encoding) throws -> Yams.Parser in Parser.o
  "_yaml_parser_parse", referenced from:
      Yams.Parser.singleRoot() throws -> Yams.Node? in Parser.o
      Yams.Parser.singleRoot() throws -> Yams.Node? in Parser.o
      Yams.Parser.nextRoot() throws -> Yams.Node? in Parser.o
      Yams.Parser.init(yaml: Swift.String, resolver: Yams.Resolver, constructor: Yams.Constructor, encoding: Yams.Parser.Encoding) throws -> Yams.Parser in Parser.o
      Yams.Parser.(startParse in _61DADACE4404A34EA4A7CBD5917BB545)(with: Swift.UnsafeBufferPointer<Swift.UInt8>) throws -> () in Parser.o
      Yams.Parser.(startParse in _61DADACE4404A34EA4A7CBD5917BB545)(with: Swift.UnsafeRawBufferPointer) throws -> () in Parser.o
      Yams.Parser.(loadDocument in _61DADACE4404A34EA4A7CBD5917BB545)() throws -> Yams.Node in Parser.o
      Yams.Parser.(loadDocument in _61DADACE4404A34EA4A7CBD5917BB545)() throws -> Yams.Node in Parser.o
      ...
  "_yaml_parser_set_encoding", referenced from:
      Yams.Parser.init(yaml: Swift.String, resolver: Yams.Resolver, constructor: Yams.Constructor, encoding: Yams.Parser.Encoding) throws -> Yams.Parser in Parser.o
      Yams.Parser.init(yaml: Swift.String, resolver: Yams.Resolver, constructor: Yams.Constructor, encoding: Yams.Parser.Encoding) throws -> Yams.Parser in Parser.o
  "_yaml_parser_set_input_string", referenced from:
      Yams.Parser.init(yaml: Swift.String, resolver: Yams.Resolver, constructor: Yams.Constructor, encoding: Yams.Parser.Encoding) throws -> Yams.Parser in Parser.o
      Yams.Parser.(startParse in _61DADACE4404A34EA4A7CBD5917BB545)(with: Swift.UnsafeBufferPointer<Swift.UInt8>) throws -> () in Parser.o
      Yams.Parser.(startParse in _61DADACE4404A34EA4A7CBD5917BB545)(with: Swift.UnsafeRawBufferPointer) throws -> () in Parser.o
  "_yaml_scalar_event_initialize", referenced from:
      Yams.Emitter.(serializeScalar in _ED6AA6759560A6062E809BF7E6589292)(Yams.Node.Scalar) throws -> () in Emitter.o
  "_yaml_sequence_end_event_initialize", referenced from:
      Yams.Emitter.(serializeSequence in _ED6AA6759560A6062E809BF7E6589292)(Yams.Node.Sequence) throws -> () in Emitter.o
  "_yaml_sequence_start_event_initialize", referenced from:
      Yams.Emitter.(serializeSequence in _ED6AA6759560A6062E809BF7E6589292)(Yams.Node.Sequence) throws -> () in Emitter.o
  "_yaml_stream_end_event_initialize", referenced from:
      Yams.Emitter.close() throws -> () in Emitter.o
  "_yaml_stream_start_event_initialize", referenced from:
      Yams.Emitter.open() throws -> () in Emitter.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

0.23 Branch:
Similar to main, the build fails due to missing the SPMSQLite3 module.
```
[Basics#50] no such module 'SPMSQLite3'
[Basics#50] /Users/blablabla/Developer/Scipio/.build/checkouts/swift-package-manager/Sources/Basics/SQLite.swift:18:8: error: no such module 'SPMSQLite3'
import SPMSQLite3
```

1. Could you add installation instructions in the main README? A step-by-step guide would be valuable for those setting up the project for the first time. It could include dependencies, any additional configurations, and a sample mint command to run the project successfully.
2. If there are known workarounds for these errors or if there are specific platform/toolchain requirements (e.g., Xcode version, macOS SDK version), adding this information to the README or a “Known Issues” section would be very useful.

How to install and run Scipio ?

Thank you for considering these suggestions!

**Comment by giginet** [comment]
Hi! We tested to pass the build with Xcode 16.0, so it's strange to fail the build 🤔 

As you pointed, it's better to improve installation guide.
We distributes Artifact Bundle on GitHub release, you can use this with this tool without build. Try this.
https://github.com/mtj0928/nest

**Comment by mackoj** [comment]
Thanks for the response. 

Do we need to have something on our computer for it to compile?

I will try nest.

**Comment by mackoj** [comment]
nest worked to install Scipio thanks @giginet.

**Comment by mackoj** [comment]
Now building main work 🤷‍♂️ I feel that it would be better if you could consider pushing the `Package.resolved` file to be sure that everyone is building the same version of Scipio @giginet. Thanks
